version: '3.9'

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - client